#' @keywords internal
"_PACKAGE"

## usethis namespace: start
#' @importFrom bslib card card_header
#' @importFrom bslib layout_column_wrap
#' @importFrom bslib layout_columns
#' @importFrom bslib layout_sidebar
#' @importFrom bslib nav_hide
#' @importFrom bslib nav_item
#' @importFrom bslib nav_panel
#' @importFrom bslib nav_select
#' @importFrom bslib nav_show
#' @importFrom bslib nav_spacer
#' @importFrom bslib page_navbar
#' @importFrom bslib popover
#' @importFrom bslib sidebar
#' @importFrom checkmate assertSubset
#' @importFrom cli cli_alert_info
#' @importFrom cli cli_alert_success
#' @importFrom cli cli_h3
#' @importFrom cli cli_status
#' @importFrom cli cli_status_update
#' @importFrom data.tree as.Node
#' @importFrom data.tree GetDefaultTooltip
#' @importFrom data.tree SetEdgeStyle
#' @importFrom data.tree SetGraphStyle
#' @importFrom data.tree SetNodeStyle
#' @importFrom DBI dbExecute
#' @importFrom DBI dbIsValid
#' @importFrom DBI dbWriteTable
#' @importFrom DBI sqlInterpolate
#' @importFrom DiagrammeR get_edge_df
#' @importFrom DiagrammeR render_graph
#' @importFrom dplyr across
#' @importFrom dplyr as_tibble
#' @importFrom dplyr bind_rows
#' @importFrom dplyr case_when
#' @importFrom dplyr desc
#' @importFrom dplyr distinct
#' @importFrom dplyr everything
#' @importFrom dplyr left_join
#' @importFrom dplyr n
#' @importFrom dplyr pull
#' @importFrom dplyr reframe
#' @importFrom dplyr row_number
#' @importFrom dplyr rowwise
#' @importFrom dplyr summarise
#' @importFrom dplyr tbl
#' @importFrom dplyr where
#' @importFrom DT datatable
#' @importFrom DT dataTableProxy
#' @importFrom DT DTOutput
#' @importFrom DT editData
#' @importFrom DT formatStyle
#' @importFrom DT renderDT
#' @importFrom DT styleEqual
#' @importFrom DT selectRows
#' @importFrom duckdb dbConnect
#' @importFrom duckdb dbDisconnect
#' @importFrom duckdb dbSendQuery
#' @importFrom duckdb dbWriteTable
#' @importFrom duckdb duckdb
#' @importFrom duckdb duckdb_shutdown
#' @importFrom ggiraph geom_errorbarh_interactive
#' @importFrom ggiraph geom_tile_interactive
#' @importFrom ggiraph opts_selection
#' @importFrom ggiraph opts_sizing
#' @importFrom ggiraph opts_zoom
#' @importFrom ggplot2 aes
#' @importFrom ggplot2 annotate
#' @importFrom ggplot2 element_blank
#' @importFrom ggplot2 element_text
#' @importFrom ggplot2 expand_limits
#' @importFrom ggplot2 expansion
#' @importFrom ggplot2 facet_grid
#' @importFrom ggplot2 geom_area
#' @importFrom ggplot2 geom_hline
#' @importFrom ggplot2 geom_smooth
#' @importFrom ggplot2 geom_text
#' @importFrom ggplot2 ggsave
#' @importFrom ggplot2 margin
#' @importFrom ggplot2 rel
#' @importFrom ggplot2 sec_axis
#' @importFrom ggplot2 theme_bw
#' @importFrom ggplot2 unit
#' @importFrom grDevices colorRampPalette
#' @importFrom grDevices colors
#' @importFrom htmltools css
#' @importFrom janitor clean_names
#' @importFrom jsonlite toJSON
#' @importFrom methods new
#' @importFrom methods setClass
#' @importFrom methods setGeneric
#' @importFrom methods setMethod
#' @importFrom methods setValidity
#' @importFrom methods signature
#' @importFrom methods validObject
#' @importFrom nloptr nloptr
#' @importFrom plotly add_annotations
#' @importFrom plotly add_markers
#' @importFrom plotly config
#' @importFrom plotly event_data
#' @importFrom plotly event_register
#' @importFrom plotly plot_ly
#' @importFrom plotly plotlyOutput
#' @importFrom plotly renderPlotly
#' @importFrom pracma trapz
#' @importFrom RaMS grabMSdata
#' @importFrom reactable colDef
#' @importFrom reactable colFormat
#' @importFrom reactable getReactableState
#' @importFrom reactable reactableOutput
#' @importFrom reactable renderReactable
#' @importFrom reticulate import_from_path
#' @importFrom reticulate py_discover_config
#' @importFrom reticulate py_install
#' @importFrom reticulate virtualenv_create
#' @importFrom rlang .data
#' @importFrom rlang .env
#' @importFrom rlang call_args
#' @importFrom RTMB getAll
#' @importFrom RTMB MakeADFun
#' @importFrom scales percent_format
#' @importFrom shiny actionButton
#' @importFrom shiny checkboxInput
#' @importFrom shiny column
#' @importFrom shiny dataTableOutput
#' @importFrom shiny div
#' @importFrom shiny downloadButton
#' @importFrom shiny downloadHandler
#' @importFrom shiny fileInput
#' @importFrom shiny fluidPage
#' @importFrom shiny fluidRow
#' @importFrom shiny getDefaultReactiveDomain
#' @importFrom shiny h2
#' @importFrom shiny h3
#' @importFrom shiny h4
#' @importFrom shiny h6
#' @importFrom shiny HTML
#' @importFrom shiny htmlOutput
#' @importFrom shiny icon
#' @importFrom shiny insertUI
#' @importFrom shiny modalButton
#' @importFrom shiny modalDialog
#' @importFrom shiny moduleServer
#' @importFrom shiny need
#' @importFrom shiny NS
#' @importFrom shiny numericInput
#' @importFrom shiny observe
#' @importFrom shiny observeEvent
#' @importFrom shiny p
#' @importFrom shiny plotOutput
#' @importFrom shiny Progress
#' @importFrom shiny radioButtons
#' @importFrom shiny reactive
#' @importFrom shiny reactiveVal
#' @importFrom shiny removeModal
#' @importFrom shiny removeUI
#' @importFrom shiny renderDataTable
#' @importFrom shiny renderPlot
#' @importFrom shiny renderPrint
#' @importFrom shiny renderText
#' @importFrom shiny renderUI
#' @importFrom shiny req
#' @importFrom shiny runApp
#' @importFrom shiny selectInput
#' @importFrom shiny selectizeInput
#' @importFrom shiny shinyApp
#' @importFrom shiny showModal
#' @importFrom shiny showNotification
#' @importFrom shiny sliderInput
#' @importFrom shiny stopApp
#' @importFrom shiny tabPanel
#' @importFrom shiny tabsetPanel
#' @importFrom shiny tagList
#' @importFrom shiny tags
#' @importFrom shiny textInput
#' @importFrom shiny textOutput
#' @importFrom shiny uiOutput
#' @importFrom shiny updateRadioButtons
#' @importFrom shiny updateSelectInput
#' @importFrom shiny updateSelectizeInput
#' @importFrom shiny updateTabsetPanel
#' @importFrom shiny validate
#' @importFrom shiny verbatimTextOutput
#' @importFrom shiny wellPanel
#' @importFrom shiny withProgress
#' @importFrom shinyalert shinyalert
#' @importFrom shinychat chat_append
#' @importFrom shinychat chat_ui
#' @importFrom shinyjs disable
#' @importFrom shinyjs enable
#' @importFrom shinyjs hide
#' @importFrom shinyjs show
#' @importFrom shinyjs useShinyjs
#' @importFrom shinyWidgets actionBttn
#' @importFrom shinyWidgets actionGroupButtons
#' @importFrom shinyWidgets pickerInput
#' @importFrom shinyWidgets show_alert
#' @importFrom stats as.formula
#' @importFrom stats coef
#' @importFrom stats complete.cases
#' @importFrom stats lm
#' @importFrom stats median
#' @importFrom stats model.matrix
#' @importFrom stats na.omit
#' @importFrom stats nlminb
#' @importFrom stats nls
#' @importFrom stats optim
#' @importFrom stats predict
#' @importFrom stats quantile
#' @importFrom stats residuals
#' @importFrom stats rstandard
#' @importFrom stats sd
#' @importFrom stats setNames
#' @importFrom stats time
#' @importFrom tibble as_tibble
#' @importFrom tibble enframe
#' @importFrom tidyr separate_wider_delim
#' @importFrom tidyselect matches
#' @importFrom tidyselect starts_with
#' @importFrom utils packageVersion
#' @importFrom utils read.delim
#' @importFrom utils write.csv
#' @importFrom uuid UUIDgenerate
#' @importFrom writexl write_xlsx
#' @importFrom xml2 xml_attrs
#' @importFrom xml2 xml_child
#' @importFrom xml2 xml_children
#' @importFrom yaml read_yaml
## usethis namespace: end
NULL
