#' @keywords internal
"_PACKAGE"

## usethis namespace: start
#' @importFrom checkmate assertSubset
#' @importFrom DBI dbIsValid
#' @importFrom DBI dbWriteTable
#' @importFrom DiagrammeR get_edge_df
#' @importFrom dplyr across
#' @importFrom dplyr as_tibble
#' @importFrom dplyr case_when
#' @importFrom dplyr desc
#' @importFrom dplyr distinct
#' @importFrom dplyr everything
#' @importFrom dplyr left_join
#' @importFrom dplyr n
#' @importFrom dplyr pull
#' @importFrom dplyr row_number
#' @importFrom dplyr summarise
#' @importFrom dplyr tbl
#' @importFrom dplyr where
#' @importFrom DT datatable
#' @importFrom DT dataTableProxy
#' @importFrom DT DTOutput
#' @importFrom DT editData
#' @importFrom DT formatStyle
#' @importFrom DT styleEqual
#' @importFrom duckdb dbConnect
#' @importFrom duckdb dbDisconnect
#' @importFrom duckdb duckdb
#' @importFrom duckdb duckdb_shutdown
#' @importFrom ggplot2 aes
#' @importFrom ggplot2 annotate
#' @importFrom ggplot2 element_blank
#' @importFrom ggplot2 element_text
#' @importFrom ggplot2 expand_limits
#' @importFrom ggplot2 expansion
#' @importFrom ggplot2 geom_area
#' @importFrom ggplot2 geom_hline
#' @importFrom ggplot2 ggsave
#' @importFrom ggplot2 margin
#' @importFrom ggplot2 rel
#' @importFrom ggplot2 sec_axis
#' @importFrom ggplot2 unit
#' @importFrom grDevices colorRampPalette
#' @importFrom grDevices colors
#' @importFrom htmltools css
#' @importFrom methods new
#' @importFrom methods validObject
#' @importFrom rlang .data
#' @importFrom shiny dataTableOutput
#' @importFrom shiny renderDataTable
#' @importFrom shinyalert shinyalert
#' @importFrom stats quantile
#' @importFrom stats time
#' @importFrom tidyselect matches
#' @importFrom tidyselect starts_with
#' @importFrom utils packageVersion
#' @importFrom utils write.csv
#' @importFrom yaml read_yaml
## usethis namespace: end
NULL
